name: flutter_master
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

# riveプラグインがnullセーフティ未対応な為、一時バージョンを下げる
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  google_fonts: ^2.0.0
  rive: ^0.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/